# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-08-02 00:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pigginderapp', '0003_auto_20190801_1829'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='receiver_id',
            new_name='receiver',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='sender_id',
            new_name='sender',
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures'),
        ),
    ]
