# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-08-02 02:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pigginderapp', '0004_auto_20190802_0049'),
    ]

    operations = [
        migrations.AddField(
            model_name='relationship',
            name='accepted',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='relationship',
            name='rejected',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='pigOne',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_by', to='pigginderapp.User'),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='pigTwo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='being_liked', to='pigginderapp.User'),
        ),
    ]
