# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-08-02 03:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pigginderapp', '0005_auto_20190802_0221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relationship',
            name='rejected',
        ),
    ]
